server {
    listen 80;

    root /var/www/devops-demo/html;
    index index.html;

    server_name <EC2_INSTANCE_PUBLIC_IP>;  # e.g. 13.233.45.67 or yourname.duckdns.org

    location / {
        try_files $uri $uri/ =404;
    }
}
